### ISSUE TITLE
NameID and email-address are not the same

### ISSUE THREAD

**Issue by phavekes** [OpenConext/Stepup-Azure-MFA#30]
When validating authentication the SAML NameID is compared to the email-address of the user. These do not need to be the same. When the NameID id different from the email-address, an error is presented to the user, but the authentication is valid.

Please compare the SAML assertion's email address to the users self-entered email address.

https://github.com/OpenConext/Stepup-Azure-MFA/blob/63bb63d63427250acd423668344e5f7c7b4c1dea/src/Surfnet/AzureMfa/Application/Service/AzureMfaService.php#L197

**Comment by pablothedude** [comment]
@phavekes the issue should be resolved in https://github.com/OpenConext/Stepup-Azure-MFA/releases/tag/1.1.3 .

Will you close the issue, if this is up to par?
